### ISSUE TITLE
[Safari 8.0.3] The Swiss cities demo jumps when changing zooming level

### ISSUE THREAD

**Issue by akauppi** [teralytics/Leaflet.D3SvgOverlay#1]
[http://bl.ocks.org/xEviL/4921fff1d70f5601d159](http://bl.ocks.org/xEviL/4921fff1d70f5601d159)

OS X 10.10.x, Safari 8.0.3
(seems to be okay in Firefox 34.0.5 and Chrome 40.0)

The current (0.8.x) Leaflet `master` has "linear scaling", which could be used by the D3 SVG overlay as well. It would animate the zoom transformation instead of the current glitchy behaviour.

**Comment by akauppi** [comment]
Hi all,

just wanting you to know that I've crafted a generic solution to using Leaflet and SVG libraries (including D3) together. Does not have issues with the zooming level. https://github.com/akauppi/Leaflet/tree/activeOverlay

It has the Swiss cities code as a demo in `debug/map/swiss-cities.html`. Is that okay for you? How should I credit you guys? Did not see an email address to send this to, so thought to place here.

**Comment by xEviL** [comment]
@akauppi sorry for the late response, when I have the time I'll have a look. Would be great to port your changes to D3SvgOverlay or maybe extract your code into another plugin like L.SvgOverlay and then D3SvgOverlay can depend on it.

**Comment by akauppi** [comment]
Hi, @xEviL 

I don't know if this is the best place to discuss the `ActiveOverlay` thingy. Let's come up with some other media if we are to do something about it.

This [PR](https://github.com/Leaflet/Leaflet/pull/3243) in the Leaflet proper has most information about the patch. The author's opinion was that it could be done as a plugin. I have little motivation to start maintaining a plugin (I just want to use the thing :) ). So it's currently not heading anywhere. If someone wants to adapt it and start maintaining, I'm very happy about that.

As I see it - without remembering your D3 overlay very closely, I'm afraid - the `ActiveOverlay` patch should pretty much render SVG library-specific bindings unneeded. It lets Leaflet run in its world, and anything SVG run in its. It makes peace between these two domains so that e.g. zooming in Leaflet does not affect _anything_ in the SVG domain.

I think this is how things should be. I also think Leaflet would indeed benefit from such functionality being built-in.

My own project is currently using Snap.svg but likely moving to svg.js later this year.

The best way to see what the patch is about is the above mentioned PR. Also - and this was one of the reasons I didn't want to start maintain it as a plugin - it would benefit from someone knowing the mindset of Leaflet better than I do. I can see the (existing) `ImageOverlay` and this should actually derive from a joint base class (but obviously this is beyond a plugin's architectural freedoms). I tried to follow the idea of the `ImageOverlay` very closely - it's just that the "picture" happens to be changing and interactive.

Any ideas - how would this benefit your D3 + Leaflet usage?

**Comment by xEviL** [comment]
Seems that the best way to address the issue and also to simplify the plugin code is to use Leaflet-provided classes for animation.

For Leaflet 0.7.x the following example shows how to inject D3 generated elements into the Leaflet's SVG layer that handles animations and scaling on it's own:
http://bl.ocks.org/monfera/11100987
The only problem here is projection that rounds the pixel coordinates and this is why in this example you see "jumps" when zooming.
Basicly, calling `map._initPathRoot()` creates the svg layer in Leaflet and then you just use it to inject your elements.

For Leaflet 1.x there's a concept of a renderer: `L.Renderer` class, that abstracts zoom animation, scaling and shifting. There this should be used by L.D3SvgOverlay.
