### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by Meekohi** [teralytics/Leaflet.D3SvgOverlay#12]
Why write this obfuscated line of code `!this.translateAnim || this.translateAnim.remove();` instead of just `if(this.translateAnim) this.translateAnim.remove();`?

https://github.com/teralytics/Leaflet.D3SvgOverlay/blob/4edb6a241b53620bff83c983e5b13d775dd5ca06/L.D3SvgOverlay.js#L73

**Comment by xEviL** [comment]
@Meekohi 
`this.translateAnim` can be `undefined`, then `if(this.translateAnim) this.translateAnim.remove();` will produce an error.

UPDATE: for properties you can indeed use the `if (obj.prop) {...}` 

Anyways I don't like the `a || b` syntax any more, in the new update all but one very intuitive usage of these are removed.

**Comment by Meekohi** [comment]
Ah interesting side-case. Thanks!
