### ISSUE TITLE
Svg layer added to layerGroup

### ISSUE THREAD

**Issue by ea42gh** [teralytics/Leaflet.D3SvgOverlay#18]
I added ad d3SvgOverlay group to a layerGroup.
Turning the layer display off results in the layer not being redrawn
when the layer is turned on again.

Workaround to redraw the layer:
turn the layer off, change the zoom level, turn the layer on again

**Comment by xEviL** [comment]
@ea42gh could you please provide an example of the code with the issue? E.g. use jsfiddle.com or modify the Swiss Cities example gist: https://gist.github.com/xEviL/4921fff1d70f5601d159

I was not able to reproduce the issue. I think LayerGroups vs Layers in Leaflet are not meant to be used together, e.g. adding both to the layer control can create a state where layer is disabled and LayerGroup is enabled - then real state of what should be shown on the map is ambiguous.

**Comment by xEviL** [comment]
Could not reproduce the issue.
