### ISSUE TITLE
scale incorrect after zoom and layer disable&enable

### ISSUE THREAD

**Issue by jonim8or** [teralytics/Leaflet.D3SvgOverlay#20]
When using the leaflet layercontrol, you can get incorrect scale after zooming in and then disable-and-enabling the d3 layer. This is because the scale value defaults to 1.

**Comment by xEviL** [comment]
@jonim8or could you provide a test case (e.g. use **gists** + http://bl.ocks.org/, **jsfiddle** or similar service). This is probably related to some issues (js errors) in your _drawCallback_ function.

**Comment by jonim8or** [comment]
Hi,

I got it working by the attached change.
Issue has to do with the layercontrol as in
http://leafletjs.com/examples/layers-control.html

Jonatan

On Fri, Mar 18, 2016 at 4:13 PM, Kirill Zhuravlev notifications@github.com
wrote:

> @jonim8or https://github.com/jonim8or could you provide a test case
> (e.g. use _gists_ + http://bl.ocks.org/, _jsfiddle_ or similar service).
> This is probably related to some issues (js errors) in your _drawCallback_
> function.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/teralytics/Leaflet.D3SvgOverlay/issues/20#issuecomment-198403807

From 559edbce5c19ebb573ffae0e89fd81e7160af4b1 Mon Sep 17 00:00:00 2001
From: "jonatan.bijl" jonatan.bijl@tba.nl
Date: Fri, 18 Mar 2016 15:26:45 +0100
Subject: [PATCH] Made layer calculate initial zoom instead of defaulting to 1.
 Then you can also disable/enable the layer without problems.

---

 L.D3SvgOverlay.js     | 2 +-
 L.D3SvgOverlay.min.js | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/L.D3SvgOverlay.js b/L.D3SvgOverlay.js
index e45ef59..f4cb2e8 100644
--- a/L.D3SvgOverlay.js
+++ b/L.D3SvgOverlay.js
@@ -125,7 +125,7 @@ L.D3SvgOverlay = (L.version < "1.0" ? L.Class : L.Layer).extend({
             unitsPerMeter: 256 \* Math.pow(2, _layer._zoom) / 40075017,
             map: _layer.map,
             layer: _layer,
-            scale: 1
-            scale: Math.pow(2, _layer._zoom) //edit by jonatan
       };
       this.projection._projectPoint = function(x, y) {
           var point = _layer.projection.latLngToLayerPoint(new L.LatLng(y, x));
  diff --git a/L.D3SvgOverlay.min.js b/L.D3SvgOverlay.min.js
  index de67be4..e2eb695 100644
  --- a/L.D3SvgOverlay.min.js
  +++ b/L.D3SvgOverlay.min.js
  @@ -4,4 +4,4 @@
  - @author Kirill Zhuravlev kirill.zhuravlev@teralytics.ch
    *
    _/
    -(function(factory){if(typeof define==="function"&&define.amd){define(["leaflet","d3"],factory)}else if(typeof module==="object"&&module.exports){module.exports=factory(require("leaflet","d3"))}else{factory(L,d3)}})(function(L,d3){if(typeof d3=="undefined"){throw"D3 SVG Overlay for Leaflet requires D3 library loaded first"}if(typeof L=="undefined"){throw"D3 SVG Overlay for Leaflet requires Leaflet library loaded first"}if(L.version>="1.0"){d3.select("head").append("style").attr("type","text/css").text("g.d3-overlay *{pointer-events:visiblePainted;}")}L.D3SvgOverlay=(L.version<"1.0"?L.Class:L.Layer).extend({includes:L.version<"1.0"?L.Mixin.Events:[],_undef:function(a){return typeof a=="undefined"},_options:function(options){if(this._undef(options)){return this.options}options.zoomHide=this._undef(options.zoomHide)?false:options.zoomHide;options.zoomDraw=this._undef(options.zoomDraw)?true:options.zoomDraw;return this.options=options},_disableLeafletRounding:function(){this._leaflet_round=L.Point.prototype._round;L.Point.prototype._round=function(){return this}},_enableLeafletRounding:function(){L.Point.prototype._round=this._leaflet_round},draw:function(){this._disableLeafletRounding();this._drawCallback(this.selection,this.projection,this.map.getZoom());this._enableLeafletRounding()},initialize:function(drawCallback,options){this._options(options||{});this._drawCallback=drawCallback},_zoomChange:function(evt){this._disableLeafletRounding();var newZoom=this._undef(evt.zoom)?this.map._zoom:evt.zoom;this._zoomDiff=newZoom-this._zoom;this._scale=Math.pow(2,this._zoomDiff);this.projection.scale=this._scale;this._shift=this.map.latLngToLayerPoint(this._wgsOrigin)._subtract(this._wgsInitialShift.multiplyBy(this._scale));var shift=["translate(",this._shift.x,",",this._shift.y,") "];var scale=["scale(",this._scale,",",this._scale,") "];this._rootGroup.attr("transform",shift.concat(scale).join(""));if(this.options.zoomDraw){this.draw()}this._enableLeafletRounding()},onAdd:function(map){this.map=map;var _layer=this;if(L.version<"1.0"){map._initPathRoot();this._svg=d3.select(map._panes.overlayPane).select("svg");this._rootGroup=this._svg.append("g")}else{this._svg=L.svg();map.addLayer(this._svg);this._rootGroup=d3.select(this._svg._rootGroup).classed("d3-overlay",true)}this._rootGroup.classed("leaflet-zoom-hide",this.options.zoomHide);this.selection=this._rootGroup;this._pixelOrigin=map.getPixelOrigin();this._wgsOrigin=L.latLng([0,0]);this._wgsInitialShift=this.map.latLngToLayerPoint(this._wgsOrigin);this._zoom=this.map.getZoom();this._shift=L.point(0,0);this._scale=1;this.projection={latLngToLayerPoint:function(latLng,zoom){zoom=_layer._undef(zoom)?_layer._zoom:zoom;var projectedPoint=_layer.map.project(L.latLng(latLng),zoom)._round();return projectedPoint._subtract(_layer._pixelOrigin)},layerPointToLatLng:function(point,zoom){zoom=_layer._undef(zoom)?_layer._zoom:zoom;var projectedPoint=L.point(point).add(_layer._pixelOrigin);return _layer.map.unproject(projectedPoint,zoom)},unitsPerMeter:256_Math.pow(2,_layer._zoom)/40075017,map:_layer.map,layer:_layer,scale:1};this.projection._projectPoint=function(x,y){var point=_layer.projection.latLngToLayerPoint(new L.LatLng(y,x));this.stream.point(point.x,point.y)};this.projection.pathFromGeojson=d3.geo.path().projection(d3.geo.transform({point:this.projection._projectPoint}));this.projection.latLngToLayerFloatPoint=this.projection.latLngToLayerPoint;this.projection.getZoom=this.map.getZoom.bind(this.map);this.projection.getBounds=this.map.getBounds.bind(this.map);this.selection=this._rootGroup;if(L.version<"1.0")map.on("viewreset",this._zoomChange,this);this.draw()},getEvents:function(){return{zoomend:this._zoomChange}},onRemove:function(map){if(L.version<"1.0"){map.off("viewreset",this._zoomChange,this);this._rootGroup.remove()}else{this._svg.remove()}},addTo:function(map){map.addLayer(this);return this}});L.D3SvgOverlay.version="2.1";L.d3SvgOverlay=function(drawCallback,options){return new L.D3SvgOverlay(drawCallback,options)}});
    \ No newline at end of file
    +(function(factory){if(typeof define==="function"&&define.amd){define(["leaflet","d3"],factory)}else if(typeof module==="object"&&module.exports){module.exports=factory(require("leaflet","d3"))}else{factory(L,d3)}})(function(L,d3){if(typeof d3=="undefined"){throw"D3 SVG Overlay for Leaflet requires D3 library loaded first"}if(typeof L=="undefined"){throw"D3 SVG Overlay for Leaflet requires Leaflet library loaded first"}if(L.version>="1.0"){d3.select("head").append("style").attr("type","text/css").text("g.d3-overlay _{pointer-events:visiblePainted;}")}L.D3SvgOverlay=(L.version<"1.0"?L.Class:L.Layer).extend({includes:L.version<"1.0"?L.Mixin.Events:[],_undef:function(a){return typeof a=="undefined"},_options:function(options){if(this._undef(options)){return this.options}options.zoomHide=this._undef(options.zoomHide)?false:options.zoomHide;options.zoomDraw=this._undef(options.zoomDraw)?true:options.zoomDraw;return this.options=options},_disableLeafletRounding:function(){this._leaflet_round=L.Point.prototype._round;L.Point.prototype._round=function(){return this}},_enableLeafletRounding:function(){L.Point.prototype._round=this._leaflet_round},draw:function(){this._disableLeafletRounding();this._drawCallback(this.selection,this.projection,this.map.getZoom());this._enableLeafletRounding()},initialize:function(drawCallback,options){this._options(options||{});this._drawCallback=drawCallback},_zoomChange:function(evt){this._disableLeafletRounding();var newZoom=this._undef(evt.zoom)?this.map._zoom:evt.zoom;this._zoomDiff=newZoom-this._zoom;this._scale=Math.pow(2,this._zoomDiff);this.projection.scale=this._scale;this._shift=this.map.latLngToLayerPoint(this._wgsOrigin)._subtract(this._wgsInitialShift.multiplyBy(this._scale));var shift=["translate(",this._shift.x,",",this._shift.y,") "];var scale=["scale(",this._scale,",",this._scale,") "];this._rootGroup.attr("transform",shift.concat(scale).join(""));if(this.options.zoomDraw){this.draw()}this._enableLeafletRounding()},onAdd:function(map){this.map=map;var _layer=this;if(L.version<"1.0"){map._initPathRoot();this._svg=d3.select(map._panes.overlayPane).select("svg");this._rootGroup=this._svg.append("g")}else{this._svg=L.svg();map.addLayer(this._svg);this._rootGroup=d3.select(this._svg._rootGroup).classed("d3-overlay",true)}this._rootGroup.classed("leaflet-zoom-hide",this.options.zoomHide);this.selection=this._rootGroup;this._pixelOrigin=map.getPixelOrigin();this._wgsOrigin=L.latLng([0,0]);this._wgsInitialShift=this.map.latLngToLayerPoint(this._wgsOrigin);this._zoom=this.map.getZoom();this._shift=L.point(0,0);this._scale=1;this.projection={latLngToLayerPoint:function(latLng,zoom){zoom=_layer._undef(zoom)?_layer._zoom:zoom;var projectedPoint=_layer.map.project(L.latLng(latLng),zoom)._round();return projectedPoint._subtract(_layer._pixelOrigin)},layerPointToLatLng:function(point,zoom){zoom=_layer._undef(zoom)?_layer._zoom:zoom;var projectedPoint=L.point(point).add(_layer._pixelOrigin);return _layer.map.unproject(projectedPoint,zoom)},unitsPerMeter:256_Math.pow(2,_layer._zoom)/40075017,map:_layer.map,layer:_layer,scale:Math.pow(2, _layer._zoom)};this.projection._projectPoint=function(x,y){var point=_layer.projection.latLngToLayerPoint(new L.LatLng(y,x));this.stream.point(point.x,point.y)};this.projection.pathFromGeojson=d3.geo.path().projection(d3.geo.transform({point:this.projection._projectPoint}));this.projection.latLngToLayerFloatPoint=this.projection.latLngToLayerPoint;this.projection.getZoom=this.map.getZoom.bind(this.map);this.projection.getBounds=this.map.getBounds.bind(this.map);this.selection=this._rootGroup;if(L.version<"1.0")map.on("viewreset",this._zoomChange,this);this.draw()},getEvents:function(){return{zoomend:this._zoomChange}},onRemove:function(map){if(L.version<"1.0"){map.off("viewreset",this._zoomChange,this);this._rootGroup.remove()}else{this._svg.remove()}},addTo:function(map){map.addLayer(this);return this}});L.D3SvgOverlay.version="2.1";L.d3SvgOverlay=function(drawCallback,options){return new L.D3SvgOverlay(drawCallback,options)}});
    \ No newline at end of file
    -- 
    1.9.0.msysgit.0

**Comment by xEviL** [comment]
@jonim8or, which version of _Leaflet_ are you using?

Could you provide a specific example when you get the issue.

I modified the example to have the layer control: http://bl.ocks.org/xEviL/0c4f628645c6c21c8b3a and I cannot reproduce it.

**Comment by jonim8or** [comment]
With that example it indeed works fine. However with a modified version of the swiss cities example, the city sizes will change. 
[bug.zip](https://github.com/teralytics/Leaflet.D3SvgOverlay/files/183755/bug.zip)

**Comment by xEviL** [comment]
Thanks for the example. Now I see what you mean. I would not consider this behavior a bug.

If you want static size circles, don't specify it in pixels but in meters, e.g. smth like:

```
.attr('r', proj.unitsPerMeter * 500)
```

**Comment by gagecarto** [comment]
I agree that this is not necessarily a but.. 

I do think it would be more intuitive to have the circle sizes remain constant by default when the zoom level changes.

**Comment by gagecarto** [comment]
When I set the radius like below I still see a change in radius on zoom events. Do I also need to assign a handler for the zoom events?
    .attr('r', proj.unitsPerMeter \* 500)

@jonim8or - did you figure out something that worked for you?

**Comment by xEviL** [comment]
@gagecarto with the issue discussed here it's supposed to change. What @jonim8or wants is for radius to be consistent between the cycle "disable + enable" the layer.
For what you want, which I presume is a constant size of objects, you need to update it in D3 _update selection_ e.g. using `projection.scale`:

```
upd.attr('r', 15 / proj.scale) // keeps circles radius = 15 regardless of zoom
```

**Comment by xEviL** [comment]
to make the size consistent over "disable + enable" of the layer, specify the size in global units, like meters, e.g. using provided conversion factor `projection.unitsPerMeter`:

```
.attr('r', proj.unitsPerMeter * 500) // keeps circles radius = 500 meters
```
