### ISSUE TITLE
TopoJSON support

### ISSUE THREAD

**Issue by martgnz** [teralytics/Leaflet.D3SvgOverlay#24]
All the examples use GeoJSON.

Does this plugin support TopoJSON?

**Comment by xEviL** [comment]
@martgnz this plugin just uses D3's built-in ability to render GeoJSON features. [TopoJSON Client API](https://github.com/mbostock/topojson/wiki/API-Reference) provides you with methods to get GeoJSON features from topology.  This is how you should use TopoJSON with L.D3SvgOverlay.
