### ISSUE TITLE
D3 4.x support

### ISSUE THREAD

**Issue by rarkins** [teralytics/Leaflet.D3SvgOverlay#25]
It would be nice if this library supported D3 4.x, particularly to take advantage of building optimised bundles of D3.

**Comment by xEviL** [comment]
@rarkins, yes, would be nice to do this. Practically, only `d3.select`, `d3.geo.path` -> `d3.geoPath`, `d3.geo.transform` -> `d3.geoTransform` are used. At least compatibility changes should be straight forward.

Packaging may be trickier if we keep single package that is compatible with both v.3 and v.4 versions of D3.

**Comment by rarkins** [comment]
Hi @xEviL, perhaps it's easier for you to bump a major version here and keep the existing v2.x using "legacy" D3 3.x? 

Something else that would be great (one day) is if you additionally published a "dist" version that bundled just the parts of D3 required, kind of like some libraries publish versions that include or don't include the necessary jQuery functions.

**Comment by johannesloetzsch** [comment]
A D3 5.x compatible version can be found [here](https://github.com/johannesloetzsch/react-leaflet-d3-svg-overlay/tree/master/src/Leaflet.D3SvgOverlay)

Thanks @teralytics @manubb @xEviL
