### ISSUE TITLE
Size dependence on initial map zoom 

### ISSUE THREAD

**Issue by i4got10** [teralytics/Leaflet.D3SvgOverlay#27]
При создании слоя запоминается зум карты. При этом все пиксельные размеры svg элементов будут зависеть от этого зума.

Это очень неудобно, если нужно инициализировать карту с разной начальной позицией.

**Comment by bkrrrr** [comment]
Even i can not read the text :). I found the same bug.

The size of the svg-objects depends on the zoom level (of the map) during initialisation.
Bigger zoom leads to smaller objects.

Not sure how to fix it.

**Comment by bkrrrr** [comment]
i just figured out its already discussed & solved in #20 
Ignore my post.

**Comment by i4got10** [comment]
@bkrrr sorry, I had not enough time to translate it, when issue was published. The answer is that you always must use `scale` to calculate size depending on zoom. Something like 

```
.attr('r', s.radius / projection.layer._scale)
```
