### ISSUE TITLE
map plots not updating for fresh set of data until zoom-in/out

### ISSUE THREAD

**Issue by nizantz** [teralytics/Leaflet.D3SvgOverlay#32]
I am usingd3SvgOverlay and am trying to send new data sets on click on getData button.
On click of the buttons I ->
- pass values for node1, node2 and node3 (each selected from respective dropdown list )
- select Lat/Lon data from the json based on the above value (plotPoints function) and pass this dataset for plotting the points on the map.

On the first dataset, this works good. On the second dataset based on new values (for node1, node2 and node3) , the points do not render until I zoom in or zoom out the map. 
Am I doing something wrong or is it an issue?

Sample code below:
```
var mapOverlay = L.d3SvgOverlay(function(sel,proj){
  sel.selectAll('circle').remove();//Removing existing circles in any.
  var dataPlot = sel.selectAll('circle').data(plots);
    dataPlot.enter()
    .append('circle')
    .attr('r',4)
    .attr('cx',function(d){return proj.latLngToLayerPoint(d.latLng).x;})
    .attr('cy',function(d){return proj.latLngToLayerPoint(d.latLng).y;})
    .attr('fill','#000')
});

function plotPoints(){
  d3.json("fixtures/sample1.json",function(data){
              var geod = [];
                geod.push(data[node1][node2][node3]);
                plots = [];
                plots = geod[0].map(function (d, i) {
                d.latLng = [+d.latitude,+d.longitude];
                return d;
            });
        mapOverlay.addTo(map);
    });
}
```

> Button with id="getData" on my page calls plotPoints() on click
```
       $('#getData').on('click', function () {
            plotPoints();
          });
```

**Comment by xEviL** [comment]
Please use the `D3`'s normal workflow for updates, e.g. have a look at this article: https://www.dashingd3js.com/lessons/d3-basic-general-update-pattern
