### ISSUE TITLE
properties change on zooming and panning

### ISSUE THREAD

**Issue by rvitter** [teralytics/Leaflet.D3SvgOverlay#33]
I have a map of Arizona counties and in some cases after panning or zooming the map, the different counties change properties. Picture examples below
![ex1](https://cloud.githubusercontent.com/assets/16578403/24263438/88ff815c-0fd3-11e7-8d69-1da31c688bac.png)
and this is after zooming and panning a few times.
![ex2](https://cloud.githubusercontent.com/assets/16578403/24263449/92e30310-0fd3-11e7-8133-bb9e92e9987a.png)
I have no idea what's going on here.
EDIT:
Its hard to see but in both cases my mouse is hovering over the bottom right county (Which is suppose to be Cochise)

This is my code where the overlay is created
```
this.createSVG = function (features) {
          var max = SHPconverter.getMax(features);
          var scale = SHPconverter.getScale(max);
          d3.select("svg").remove();
          var d3Overlay = L.d3SvgOverlay(function(selection, projection) {
            var updateSelection = selection.selectAll('path').data(features.filter(
              function(v){
                if ($('.getData').prop("checked") == true) {
                  if(v.properties.hasOwnProperty('count')) { return v; }
                }
                else { return v }
              }))
            updateSelection.enter()
                .append('path')
                .attr("id", "#geog")
                .attr('d', function(d) {
                  return projection.pathFromGeojson(d);
                })
                .attr('stroke', 'white')
                .attr('fill', function(d) {
                  if ($('.getData').prop("checked") == false) { return '#ea443c' }
                  else { return scale(d.properties.count) }
                })
                .attr('fill-opacity', SHPconverter.opacity)
                .attr('stroke-width', SHPconverter.stroke_width)
                .attr('style', 'pointer-events:visiblePainted;')
                .on('click', function() {
                  var clickedGeo = this;
                  //d3.select(this).moveToBack();
                  SHPconverter.getGeogName(clickedGeo);
                })
                .on('mouseover', function(d) {
                    d3.select(this).moveToFront();
                    d3.select(this).attr('stroke', '#4bdded');
                    d3.select(this).attr('fill-opacity', SHPconverter.opacity - 0.1);
                    var clickedGeo = this;
                    var htmlList = SHPconverter.updateInfoBox(clickedGeo);
    								var xPosition = d3.select(this).attr("cx");
    								var yPosition = d3.select(this).attr("cy");
    								d3.select("#tooltip")
    									.style("left", (d3.event.pageX - 60) + "px")
                    					.style("top", (d3.event.pageY - 160) + "px")
    									.select("#labels")
    									.html(htmlList)
    								d3.select("#tooltip").classed("hidden", false);
                })
                .on('mouseout', function(d) {
                    d3.select(this).attr('fill-opacity', SHPconverter.opacity);
                    d3.select(this).attr('stroke', 'white');
                    d3.select("#tooltip").classed("hidden", true);
                })
          });
          d3Overlay.addTo(SHPconverter.map);
          $('.modal').hide();
          SHPconverter.checkForData(scale);
        }
```
EDIT 2:
I believe it may have something to do with my functions for moving layers back and forth, cant seem to replicate the problem once I remove them.
```
d3.selection.prototype.moveToFront = function() {
          return this.each(function(){
            this.parentNode.appendChild(this);
          });
        };
        d3.selection.prototype.moveToBack = function() {
            return this.each(function() {
                var firstChild = this.parentNode.firstChild;
                if (firstChild) {
                    this.parentNode.insertBefore(this, firstChild);
                }
            });
        };
```
if that's the case then what would be the best way to move layers back and forth for d3svgoverlay?

**Comment by xEviL** [comment]
I would suggest that instead you create 2 overlays, one for county shapes and one for tooltips. Then the order in which you add these to the map will determine which layer is rendered on top of which (later elements in SVG are always on top). Then make use of the d3 update functionality, which does not require recreating the layer or by-hand manipulation of DOM.

**Comment by rvitter** [comment]
I'll give that a try, though I still have no idea how any of this would be causing the shapes to change properties.
In this picture, I'm hovering over Cochise county and its showing the correct properties
![ex3](https://cloud.githubusercontent.com/assets/16578403/24298120/6b772b00-107b-11e7-9a7f-07ede2738e5e.png)
However, after zooming and panning the map a few times, I hover over Cochise county again and its showing me all of the properties of Apache county instead 
![ex4](https://cloud.githubusercontent.com/assets/16578403/24298185/9d58ca16-107b-11e7-89ae-67bd38d727d7.png)
Again, I haven't been able to replicate this when I remove the moving forward and backwards functions, but I still don't see how those could cause the shapes properties to change. When the properties do change it always seems to be to another counties property that is near. very confused by this, not sure what the problem is with the code that moves layers and the zooming function of d3svgoverlay

**Comment by xEviL** [comment]
Well, you manipulate the DOM tree (reorder elements) outside D3. D3 is not aware of that and likely you get the next or previous data payload that does not match the element in the DOM.

Instead of modifying the DOM tree, refactor your code to:
* A layer with counties, e.g. `var counties = [...]` => `CountyOverlay`;
* A layer with an overlay rendered from some state variable, e.g. `var currentCounty = [{...}]` => `TooltipOverlay`;
* Now make the `CountyOverlay` elements:
  * update the state variable `currentCounty` (mouseenter: put it into `currentCounty`, mouseleave: remove from `currentCounty`);
  * trigger redraw of `TooltipOverlay`;
