### ISSUE TITLE
How to keep stroke width unchanged during zooming?

### ISSUE THREAD

**Issue by ZuchaoWang** [teralytics/Leaflet.D3SvgOverlay#4]
Hi, in the [swiss city example](http://bl.ocks.org/xEviL/4921fff1d70f5601d159), I find the width of the circle boundaries changed during zooming. Although in the css, the width is defined as:

```
.attr('stroke-width',1)
```

but it scales with the svg during zooming. Is there any way to keep the width unchanged?

**Comment by ZuchaoWang** [comment]
Ok, I find the answer is:

```
.attr('stroke-width',1/this._scale)
```

**Comment by xEviL** [comment]
Yeap, I will probably add smth like `scaleInvar = 1/this._scale` to the projection object in future, it's very useful for creating scale-invariant sizing.

**Comment by jonataswalker** [comment]
Hi guys,

Could you please take a look at [this plunker](http://embed.plnkr.co/tTazJeyMrlF0oae2PEX6/preview) and tell me if I'm missing something? I mean, it's an animation path, a street route, but if zooming to the max the stroke is too large.

Many thanks.

**Comment by xEviL** [comment]
@jonataswalker look at the above answer from @ZuchaoWang, basically by default the drawing callback function is called again on every zoom event. You can use _D3 update selection_ of your path to update its attributes (incl. stroke-width) accordingly.

**Comment by jonataswalker** [comment]
@xEviL thanks. I'll try it. BTW, do you have some other examples of your overlay implementation?
