### ISSUE TITLE
Adding Tooltips

### ISSUE THREAD

**Issue by lfarrell** [teralytics/Leaflet.D3SvgOverlay#8]
Really nice library, particularly for someone more familiar with D3 than Leaflet. I was wondering if there is anyway to add a tooltip on mouseover or click?

**Comment by lfarrell** [comment]
I found a solution, though it might be a bit of a hack, by using @aratcliffe Leaflet tooltip library to add a tooltip inside the D3SvgOverlay object.
      ```
       var circles = document.querySelectorAll('.d3-overlay circle');

``````
    for(var i=0; i<circles.length; i++) {
        L.tooltip({
            target: circles[i],
            map: map,
            html: data[i].name,
            showDelay: 100,
            hideDelay: 100
        });
    }
    ```
``````

**Comment by xEviL** [comment]
when you create elements with D3 you can just attach an event listener to them:

```
updSel.enter()
        .append(...)
        .on("click", function(d) {
                //show tooltip based on the data d bound to element that was clicked; 
        });
```

see more in https://github.com/mbostock/d3/wiki/Selections#on
