### ISSUE TITLE
the SVG moves out of place for zoom = 1 or 0

### ISSUE THREAD

**Issue by Fil** [teralytics/Leaflet.D3SvgOverlay#9]
At zoom levels where the world map is too small to cover the window, the svg moves randomly (??) and the contents are wildly out of place.

To view it adapt the Swiss cities examples with (much) larger circles and zoom out (bug present with FF, Chrome and Safari on OSX).

![capture d ecran 2015-09-01 15 16 59](https://cloud.githubusercontent.com/assets/7001/9605192/895bcb42-50bc-11e5-94ce-b85c0823d8eb.png)

**Comment by xEviL** [comment]
@Fil, thank you for reporting the bug

**Comment by Fil** [comment]
:+1:
